version: '3'
services:
  app:
    build: .
    environment:
      - DEBUG=true
    ports:
      - "80:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=example
