
name: Bad CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        run: git clone https://github.com/AndrewVabishchevichK3123/DevOps-Cloud-labs
      
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          
      - name: Run tests
        run: |
          echo "Skipping tests..."
      
      - name: Deploy
        run: |
           echo "Deploying..."
      
      - name: Cleanup
        run: |
          echo "Cleaning up..."
          rm -rf /build
