name: CI/CD Workflow

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Debug directory
        run: |
          echo "Debugging directory:"
          pwd
          ls -la

      - name: Install dependencies
        run: |
          if [ ! -f "package.json" ]; then
            echo "Error: package.json not found!"
            exit 1
          fi
          npm install

      - name: Build
        run: npm run build
