#Goodci.yml
stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: my-app
  DOCKER_TAG: $CI_COMMIT_SHA
  CACHE_REGISTRY: registry.gitlab.com/my-app/cache

before_script:
  - echo "Preparing environment..."

build_job:
  stage: build
  script:
    - echo "Starting build with cache..."
    - docker build --cache-from $CACHE_REGISTRY -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - develop
    - master

test_job:
  stage: test
  script:
    - echo "Starting tests..."
    - pytest tests/
  parallel:
    matrix:
      - PYTHON_VERSION: 3.8
      - PYTHON_VERSION: 3.9
  only:
    - develop
    - master

deploy_job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - kubectl set image deployment/my-app my-app=$DOCKER_IMAGE:$DOCKER_TAG --record
  environment:
    name: production
  only:
    - master
