name: Bad CI/CD Without NPM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Ошибка: Неправильная проверка репозитория
      - name: Checkout code
        run: git clone https://github.com/AndrewVabishchevichK3123/DevOps-Cloud-labs
      
      # Ошибка: Установка зависимостей без указания используемого инструмента
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          apt-get update
          apt-get install -y python3 pip3
          
      # Ошибка: Отсутствие проверки тестов
      - name: Run tests
        run: |
          echo "Skipping tests..."
      
      # Ошибка: Неправильная сборка (путь может быть некорректным)
      - name: Build project
        run: |
          echo "Building project..."
          mkdir build
          cp -r src/* build/
      
      # Ошибка: Использование неправильного сервера для деплоя
      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          scp -r build/* user@production-server:/var/www/my-app
          echo "Deployment complete."
      
      # Ошибка: Удаление важных файлов
      - name: Cleanup
        run: |
          echo "Cleaning up..."
          rm -rf /build
