name: Bad CI/CD Example

on: push

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          npm install
          npm install -g some-package

      - name: Test
        run: npm test

      - name: Unsafe Secrets Handling
        run: echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"

      - name: Cleanup
        run: |
          rm -rf ./*
          echo "Cleanup completed."
