name: Bad CI/CD

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm init -y
          npm install
          npm install -g some-global-package
          echo "Dependencies installed."

      - name: Run tests
        run: |
          echo "Running tests..."
          npm test || echo "Tests failed, but continuing..."
          echo "Tests finished."

      - name: Build project
        run: |
          echo "Building the project..."
          npm run build
          echo "Using secret: ${{ secrets.SECRET_KEY }}"
          echo "Build completed."

      - name: Deploy to production
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Deploying to production..."
          scp -o StrictHostKeyChecking=no -r dist/* user@production-server:/var/www/
          echo "Deployed successfully."

      - name: Cleanup
        run: |
          echo "Cleaning up..."
          rm -rf node_modules/
          rm -rf dist/
          echo "Cleanup completed."
