name: BadCI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          echo "Starting build..."
          docker build -t my-app:latest .
          echo "Build finished."

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          echo "Starting tests..."
          pytest tests/
          echo "Tests finished."

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Deploy Application
        run: |
          echo "Deploying to production..."
          scp -r ./app user@production:/var/www/my-app
        env:
          PRODUCTION_SERVER: ${{ secrets.PRODUCTION_SERVER }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
