name: Bad CI/CD Without NPM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Ошибка: Неправильная проверка репозитория
      - name: Checkout code
        run: git clone https://github.com/AndrewVabishchevichK3123/DevOps-Cloud-labs
      
      # Ошибка: Установка зависимостей без указания используемого инструмента
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          
      # Ошибка: Отсутствие проверки тестов
      - name: Run tests
        run: |
          echo "Skipping tests..."
      
      # Ошибка: Использование неправильного сервера для деплоя
      - name: Deploy to production
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H production-server >> ~/.ssh/known_hosts
          
          echo "Deploying to production..."
          rsync -avz DevOps-Cloud-labs/ user@production-server:/var/www/my-app
          echo "Deployment complete."
      
      # Ошибка: Удаление важных файлов
      - name: Cleanup
        run: |
          echo "Cleaning up..."
          rm -rf /build
