name: Bad CI/CD Example

on: push

jobs:
  ci-cd-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          apt-get update && apt-get install -y python3 pip
          pip install pytest

      - name: Build and Test
        run: |
          echo "Starting build and tests..."
          docker build -t my-app:latest .
          pytest tests/
          echo "Build and tests completed."

      - name: Unsafe Secrets Handling
        run: echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"

      - name: Deploy to Production
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Deploying application..."
          scp -r ./app user@192.168.1.1:/var/www/my-app
          echo "Deployed successfully to production."

      - name: Cleanup
        run: |
          rm -rf ./*
          echo "Cleanup completed."
