name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pip install -r lab03/requirements.txt

      - name: Run tests
        run: |
          echo "Running tests..."
          if [ -d tests ]; then
            pytest tests
          else
            echo "No tests found. Skipping test step."
          fi
      
      - name: Build application
        run: |
          echo "Building application..."
          if [ -d src ]; then
            mkdir -p build
            cp -r src/* build/
            echo "Build complete."
          else
            echo "Directory 'src' does not exist. Skipping build step."
          fi

      - name: Deploy to production
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: /var/www/my-app
        run: |
          echo "Deploying to production server..."
          scp -o StrictHostKeyChecking=no -r build/* $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH
          echo "Deployment complete."

      - name: Cleanup
        run: |
          echo "Cleaning up local build files..."
          rm -rf build
